public enum Move {
    Absorb(Type.Grass, 20, Move_Cat.Special), Acid(Type.Poison, 40, Move_Cat.Special), Aerial_Ace(Type.Flying, 60, Move_Cat.Physical), 
    Aeroblast(Type.Flying, 100, Move_Cat.Special), Air_Cutter(Type.Flying, 55, Move_Cat.Special), Ancientpower(Type.Rock, 60, Move_Cat.Special), 
    Arm_Thrust(Type.Fight, 15, Move_Cat.Physical), Astonish(Type.Ghost, 30, Move_Cat.Physical), Aurora_Beam(Type.Ice, 65, Move_Cat.Special), 
    Barrage(Type.Normal, 15, Move_Cat.Physical), Beat_Up(Type.Dark, 10, Move_Cat.Physical), Bind(Type.Normal, 15, Move_Cat.Physical),
    Bite(Type.Dark, 60, Move_Cat.Physical), Blast_Burn(Type.Fire, 150, Move_Cat.Special), Blaze_Kick(Type.Fire, 85, Move_Cat.Physical), 
    Blizzard(Type.Ice, 120, Move_Cat.Special), Body_Slam(Type.Normal, 85, Move_Cat.Physical), Bone_Club(Type.Ground, 65, Move_Cat.Physical), 
    Bone_Rush(Type.Ground, 25, Move_Cat.Physical), Bonemerang(Type.Ground, 50, Move_Cat.Physical), Bounce(Type.Flying, 85, Move_Cat.Physical), 
    Brick_Break(Type.Fight, 75, Move_Cat.Physical), Bubble(Type.Water, 20, Move_Cat.Special), Bubble_Beam(Type.Water, 65, Move_Cat.Special),
    Bullet_Seed(Type.Grass, 10, Move_Cat.Physical), Clamp(Type.Water, 35, Move_Cat.Physical), Comet_Punch(Type.Normal, 18, Move_Cat.Physical), 
    Confusion(Type.Psychic, 50, Move_Cat.Special), Constrict(Type.Normal, 10, Move_Cat.Physical), Covet(Type.Normal, 40, Move_Cat.Physical), 
    Crabhammer(Type.Water, 90, Move_Cat.Physical), Cross_Chop(Type.Fight, 100, Move_Cat.Physical), Crunch(Type.Dark, 80, Move_Cat.Physical), 
    Crush_Claw(Type.Normal, 75, Move_Cat.Physical), Cut(Type.Normal, 50, Move_Cat.Physical), Dig(Type.Ground, 60, Move_Cat.Physical), 
    Dive(Type.Water, 60, Move_Cat.Physical), Dizzy_Punch(Type.Normal, 70, Move_Cat.Physical), Doom_Desire(Type.Steel, 120, Move_Cat.Special),
    Double_Kick(Type.Fight, 30, Move_Cat.Physical), Double_Edge(Type.Normal, 120, Move_Cat.Physical), Doubleslap(Type.Normal, 15, Move_Cat.Physical), 
    Dragon_Claw(Type.Dragon, 80, Move_Cat.Physical), Dragon_Rage(Type.Dragon, 40, Move_Cat.Special), Dragonbreath(Type.Dragon, 60, Move_Cat.Special),
    Dream_Eater(Type.Psychic, 100, Move_Cat.Special), Drill_Peck(Type.Flying, 80, Move_Cat.Physical), Dynamicpunch(Type.Fight, 100, Move_Cat.Physical), 
    Earthquake(Type.Ground, 100, Move_Cat.Physical), Egg_Bomb(Type.Normal, 100, Move_Cat.Physical), Ember(Type.Fire, 40, Move_Cat.Special),
    Explosion(Type.Normal, 250, Move_Cat.Physical), Extrasensory(Type.Psychic, 80, Move_Cat.Special), Extremespeed(Type.Normal, 80, Move_Cat.Physical),
    Facade(Type.Normal, 70, Move_Cat.Physical), Faint_Attack(Type.Dark, 60, Move_Cat.Physical), Fake_Out(Type.Normal, 40, Move_Cat.Physical),
    Fasle_Swipe(Type.Normal, 40, Move_Cat.Physical), Fire_Blast(Type.Fire, 120, Move_Cat.Special), Fire_Punch(Type.Fire, 75, Move_Cat.Physical),
    Fire_Spin(Type.Fire, 15, Move_Cat.Special), Flame_Wheel(Type.Fire, 60, Move_Cat.Physical), Flamethrower(Type.Fire, 95, Move_Cat.Special),
    Fly(Type.Flying, 70, Move_Cat.Physical), Focus_Punch(Type.Fight, 150, Move_Cat.Physical), Frenzy_Plant(Type.Grass, 150, Move_Cat.Special),
    Fury_Attack(Type.Normal, 15, Move_Cat.Physical),Fury_Cutter(Type.Bug, 10, Move_Cat.Physical), Fury_Swipes(Type.Normal, 10, Move_Cat.Physical),
    Future_Sight(Type.Psychic, 80, Move_Cat.Special), Giga_Drain(Type.Grass, 60, Move_Cat.Special), Gust(Type.Flying, 40, Move_Cat.Special),
    Headbutt(Type.Normal, 70, Move_Cat.Physical), Heat_Wave(Type.Fire, 100, Move_Cat.Special), Hi_Jump_Kick(Type.Fight, 85, Move_Cat.Physical),
    Horn_Attack(Type.Normal, 65, Move_Cat.Physical), Hydro_Cannon(Type.Water, 150, Move_Cat.Special), Hydro_Pump(Type.Water, 150, Move_Cat.Special),
    Hyper_Beam(Type.Normal, 150, Move_Cat.Special), Hyper_Fang(Type.Normal, 80, Move_Cat.Physical), Hyper_Voice(Type.Normal, 90, Move_Cat.Special),
    Ice_Ball(Type.Ice, 30, Move_Cat.Physical), Ice_Beam(Type.Ice, 95, Move_Cat.Special), Ice_Punch(Type.Ice, 65/*its really 75*/, Move_Cat.Physical),
    Icicle_Spear(Type.Ice, 10, Move_Cat.Physical), Icy_Wind(Type.Ice, 55, Move_Cat.Special), Jump_Kick(Type.Fight, 70, Move_Cat.Physical),
    Karate_Chop(Type.Fight, 55, Move_Cat.Physical), Knock_Off(Type.Dark, 20, Move_Cat.Physical), Leaf_Blade(Type.Grass, 70, Move_Cat.Physical),
    Leech_Life(Type.Bug, 20, Move_Cat.Physical), Lick(Type.Ghost, 20, Move_Cat.Physical), Mach_Punch(Type.Fight, 40, Move_Cat.Physical),
    Magical_Leaf(Type.Grass, 60, Move_Cat.Special), Mega_Drain(Type.Grass, 40, Move_Cat.Special), Mega_Kick(Type.Normal, 120, Move_Cat.Physical),
    Mega_Punch(Type.Normal, 80, Move_Cat.Physical), Mega_Horn(Type.Bug, 120, Move_Cat.Physical), Metal_Claw(Type.Steel, 50, Move_Cat.Physical),
    Meteor_Mash(Type.Steel, 100, Move_Cat.Physical), Mud_Shot(Type.Ground, 55, Move_Cat.Special), Mud_Slap(Type.Ground, 20, Move_Cat.Special),
    Muddy_Water(Type.Water, 95, Move_Cat.Special), Needle_Arm(Type.Grass, 60, Move_Cat.Physical), Outrage(Type.Dragon, 90, Move_Cat.Physical),
    Overheat(Type.Fire, 140, Move_Cat.Special), Pay_Day(Type.Normal, 40, Move_Cat.Physical), Peck(Type.Flying, 35, Move_Cat.Physical),
    Petal_Dance(Type.Grass, 70, Move_Cat.Special), Pin_Missile(Type.Bug, 14, Move_Cat.Physical), Poison_Fang(Type.Poison, 50, Move_Cat.Physical),
    Poison_Sting(Type.Poison, 15, Move_Cat.Physical), Poison_Tail(Type.Poison, 50, Move_Cat.Physical), Pound(Type.Normal, 40, Move_Cat.Physical),
    Powder_Snow(Type.Ice, 40, Move_Cat.Special), Psybeam(Type.Psychic, 65, Move_Cat.Special), Psychic(Type.Psychic, 90, Move_Cat.Special),
    Pursuit(Type.Dark, 40, Move_Cat.Physical), Quick_Attack(Type.Normal, 40, Move_Cat.Physical), Rage(Type.Normal, 20, Move_Cat.Physical),
    Rapid_Spin(Type.Normal, 20, Move_Cat.Physical), Razor_Leaf(Type.Grass, 55, Move_Cat.Physical), Razor_Wind(Type.Normal, 80, Move_Cat.Special),
    Revenge(Type.Fight, 60, Move_Cat.Physical), Rock_Blast(Type.Rock, 25, Move_Cat.Physical), Rock_Slide(Type.Rock, 75, Move_Cat.Physical),
    Rock_Smash(Type.Fight, 20, Move_Cat.Physical), Rock_Throw(Type.Rock, 50, Move_Cat.Physical), Rock_Tomb(Type.Rock, 50, Move_Cat.Physical),
    Rolling_Kick(Type.Fight, 60, Move_Cat.Physical), Rollout(Type.Rock, 30, Move_Cat.Physical), Sand_Tomb(Type.Ground, 15, Move_Cat.Physical),
    Scratch(Type.Normal, 40, Move_Cat.Physical), Secret_Power(Type.Normal, 70, Move_Cat.Physical), Selfdestruct(Type.Normal, 200, Move_Cat.Physical),
    Shadow_Ball(Type.Ghost, 80, Move_Cat.Special), Shadow_Punch(Type.Ghost, 60, Move_Cat.Physical), Shock_Wave(Type.Electric, 60, Move_Cat.Special),
    Signal_Beam(Type.Bug, 75, Move_Cat.Special), Silver_Wind(Type.Bug, 60, Move_Cat.Special), Skull_Bash(Type.Normal, 100, Move_Cat.Physical),
    Sky_Attack(Type.Flying, 140, Move_Cat.Physical), Sky_Uppercut(Type.Fight, 85, Move_Cat.Physical), Slam(Type.Normal, 80, Move_Cat.Physical),
    Slash(Type.Normal, 70, Move_Cat.Physical), Sludge(Type.Poison, 65, Move_Cat.Special), Sludge_Bomb(Type.Poison, 90, Move_Cat.Special),
    Smelling_Salts(Type.Normal, 60, Move_Cat.Physical), Smog(Type.Poison, 40, Move_Cat.Special), Snore(Type.Normal, 40, Move_Cat.Special),
    Solar_Beam(Type.Grass, 120, Move_Cat.Special), Spark(Type.Electric, 65, Move_Cat.Physical), Spike_Cannon(Type.Normal, 20, Move_Cat.Physical),
    Steel_Wing(Type.Steel, 70, Move_Cat.Physical), Stomp(Type.Normal, 65, Move_Cat.Physical), Strength(Type.Normal, 80, Move_Cat.Physical),
    Struggle(Type.Normal, 50, Move_Cat.Physical), Submission(Type.Fight, 80, Move_Cat.Physical), Superpower(Type.Fight, 120, Move_Cat.Physical),
    Surf(Type.Water, 95, Move_Cat.Special), Swift(Type.Normal, 60, Move_Cat.Special), Tackle(Type.Normal, 35, Move_Cat.Physical),
    Take_Down(Type.Normal, 90, Move_Cat.Physical), Thief(Type.Dark, 40, Move_Cat.Physical), Thrash(Type.Normal, 90, Move_Cat.Physical),
    Thunder(Type.Electric, 120, Move_Cat.Special), Thunderbolt(Type.Electric, 95, Move_Cat.Special), Thunderpunch(Type.Electric, 75, Move_Cat.Physical),
    Thundershock(Type.Electric, 40, Move_Cat.Special), Tri_Attack(Type.Normal, 80, Move_Cat.Special), Triple_Kick(Type.Fight, 10, Move_Cat.Physical),
    Twineedle(Type.Bug, 20, Move_Cat.Physical), Twister(Type.Dragon, 40, Move_Cat.Special), Uproar(Type.Normal, 50, Move_Cat.Special), 
    Vicegrip(Type.Normal, 55, Move_Cat.Physical), Vine_Whip(Type.Grass, 35, Move_Cat.Physical), Vital_Throw(Type.Fight, 70, Move_Cat.Physical),
    Volt_Tackle(Type.Electric, 120, Move_Cat.Physical), Water_Gun(Type.Water, 40, Move_Cat.Special), Water_Pulse(Type.Water, 60, Move_Cat.Special),
    Waterfall(Type.Water, 80, Move_Cat.Physical), Weather_Ball(Type.Normal, 50, Move_Cat.Special), Whirlpool(Type.Water, 15, Move_Cat.Special),
    Wing_Attack(Type.Flying, 60, Move_Cat.Physical), Wrap(Type.Normal, 15, Move_Cat.Physical), Zap_Cannon(Type.Electric, 120, Move_Cat.Special),
    Reflect(Type.Psychic, 0, Move_Cat.Other), Light_Screen(Type.Psychic, 0, Move_Cat.Other);
    Type type;
    double power;
    Move_Cat category;
    private Move(Type type, double power, Move_Cat category){
        this.type = type;
        this.power = power;
        this.category = category;
    }
}